### ISSUE TITLE
Dear Dork Master, Make Grid Great Again

### ISSUE THREAD

**Issue by chasegiunta** [chrisrowe/tailwindcss-grid#10]
I've never seen such a half-ass implementation in my ~ass~ life.

Implement grid fully or don't waste my precious time that could be spent catching up with the young kids learning dance moves derived from the popular multiplayer gaming hit, _Fortnite_.

Here's some items that are missing: https://css-tricks.com/snippets/css/complete-guide-grid/

Thanks for nothing.

**Comment by chrisrowe** [comment]
@chasegiunta PR or GTFO

**Comment by chasegiunta** [comment]
I can't risk someone landing on this issue, thinking I'm actually serious, and my internet celebrity reputation being tarnished forever...
