### ISSUE TITLE
"included in multiple rulesets" compiling error since Tailwind 1.2.0

### ISSUE THREAD

**Issue by danielbachhuber** [chrisrowe/tailwindcss-grid#11]
Tailwind v1.2.0 adds a `.grid` display utility class, which results in this compiling error:

```
`@apply` cannot be used with .grid because .grid is included in multiple rulesets.
```

See original thread in https://github.com/tailwindcss/discuss/issues/438

The solution is _probably_ to remove tailwindcss-grid, given it's now duplicated functionality, but it would be nice to be able to upgrade to Tailwind v1.2.0 without modifying a bunch of markup.

**Comment by chrisrowe** [comment]
Right yea now this functionality is mostly if not all covered in core I'd drop this from your stack?

**Comment by danielbachhuber** [comment]
Yeah, it's just going to require changing a lot of class names.

**Comment by chrisrowe** [comment]
Yeah, good luck. Find and replace all is your friend!
