### ISSUE TITLE
grid-template-rows not 

### ISSUE THREAD

**Issue by timeshift92** [chrisrowe/tailwindcss-grid#6]

**Comment by chrisrowe** [comment]
@timeshift92 can you elaborate a bit more?

**Comment by timeshift92** [comment]
```
<div
  class="grid border border-purple-500 grid-columns-3 grid-rows-3 grid-gap-3">
  <div class="bg-red-500 area-1/1/4/1">one</div>
  <div class="bg-green-500">two</div>
  <div class="bg-yellow-500">three</div>
</div>
```
class grid-rows not  included
and area-1/1/4/1 not included

if you want can make pr?

**Comment by timeshift92** [comment]
wanted to offer maybe you can use prefixes so:
grid-template-columns = gtc
grid-template-rows = grc
grid-area = ga
grid-gap = gp

**Comment by timeshift92** [comment]
in my opinion col and row is not associated with grid-column and grid-row better 'gc' and 'gr'

**Comment by timeshift92** [comment]
now I tried to play half of the function and realized that it is better to write CSS - grid manually without the utility 
for example, an area for 12 columns creates more than 100,000 combinations
